#!/bin/bash


rootCRADLEfile=../../../../data333/lecanuet/data/
rootGeant4file=../../../data333/lecanuet/Result/Systematics/Cuts/PlasticStep/


rm -rf tempory/*

usage() {
  echo "Usage: $0 [OPTIONS]"
  echo "Options:"
  echo "  nucleus=        Specify the nucleus (nucleus=32Ar)"
  echo "  N=              Specify the number of threads"
  echo "  events=         Specify the number of events"
  echo "  energy=         Specify the value of energy."
  echo "  particle=       Specify the particle."
  echo "  --help          Show this help message."
  exit 1
}

RED="\e[1;31m"
GREEN="\e[1;32m"
YELLOW="\e[1;33m"
COLOR="\e[0m"

while [[ $# -gt 0 ]]; do
  case "$1" in
    nucleus=*)
      Nuclei="${1#*=}"
      ;;
    N=*)
      N="${1#*=}"
      ;;
    events=*)
      events="${1#*=}"
      ;;
    x=*)
      x="${1#*=}"
      ;;
    y=*)
      y="${1#*=}"
      ;;
    z=*)
      z="${1#*=}"
      ;;
    theta=*)
      theta="${1#*=}"
      ;;
    step=*)
      step="${1#*=}"
      ;;
    --help)
      usage
      ;;
    *)
      echo "Argument inconnu : $1"
      exit 1
      ;;
  esac
  shift
done

suffixe="e-_PlasticStep${step}"

###default value
DEFAULT_N=3
DEFAULT_events=10000000
DEFAULT_step=0.1

events=${events:-$DEFAULT_events}
step=${step:-$DEFAULT_step}

## file file exist dont do it 
if [ -f "${rootGeant4file}${suffixe}.root" ]; then
    echo -e "$YELLOW File ${rootGeant4file}${suffixe}.root already exists. Skipping simulation. $COLOR"
    exit 0
fi

cp macro_plasticstep.mac tempory/macro_${suffixe}_bis.mac  

sed -e "s|%s|${step} mm|g; s|%threads|${N}|g; s|%output|${rootGeant4file}${suffixe}.root|g; s/%events/${events}/g;  " tempory/macro_${suffixe}_bis.mac > tempory/macro_${suffixe}.mac
#rm tempory/macro_${suffixe}_bis.mac
wisard tempory/macro_${suffixe}.mac 
echo -e "$GREEN wisard tempory/macro_${suffixe}.mac $COLOR"

Duree=$(($TimeEnd-$TimeStart))
Second=$(printf "%02d" "$(($Duree%60))")
Minute=$(printf "%02d" "$((($Duree/60)%60))")
Heure=$(printf "%02d" "$((($Duree/3600)%24))")
Jour=$(printf "%d" "$((($Duree/(3600*24))))")
echo -e "$RED Duree total : ${Jour}"
