#---------------------------------------------------------------
#   Verbosity
#---------------------------------------------------------------
/run/initialize
/run/verbose      0
/event/verbose    0
/tracking/verbose 0

#---------------------------------------------------------------
#   Input Files
#---------------------------------------------------------------
#/input/Open_B MAGNETIC_FIELD_data/wisard_field.txt
/input/Open_SRIM SRIM_data/32Ar.txt
/input/Open_CRADLE CRADLE_data/SAMPLE.root

#---------------------------------------------------------------
#   Simulation Parameters
#---------------------------------------------------------------
/Magnetic_Field 4 T
/Threshoold_PlasticScintillator 100 keV
#/Delta_Position_PlasticScintillator

#---------------------------------------------------------------
#   Systematic Variables
#---------------------------------------------------------------
/SiDeadLayer_Thickness 100 nm
/Beam_Size 2 mm 300 um
/Beam_Position 0 cm 0 cm
/Catcher_Position_z 0 mm
/Catcher_Position catcher2 0 deg     position:[source / catcher2 / catcher1] #delta angle(degree)
/Catcher_MylarDeltaThickness 0 um

#---------------------------------------------------------------
#   Generate Events
#---------------------------------------------------------------
/run/printProgress 10000
/output SAMPLE.root
/run/beamOn 20000
