#---------------------------------------------------------------
#   Verbosity
#---------------------------------------------------------------
/run/initialize
/run/verbose      0
/event/verbose    0
/tracking/verbose 1

#---------------------------------------------------------------
#   Input Files
#---------------------------------------------------------------
#/input/Open_B MAGNETIC_FIELD_data/wisard_field.txt
/Input/SRIM SRIM_data/AlMylar_32Ar.root
/Input/CRADLE /data333/lecanuet/data/Systematics/32Ar_IAS_a1.0_b0.0.root

#---------------------------------------------------------------
#   Simulation Parameters
#---------------------------------------------------------------
/Run/Threshold_PlasticScintillator 100 keV
/Run/Threads 1

/Beam/X 0.0536 mm
/Beam/Y -0.4103 mm
/Beam/Radius 1000 mm
/Beam/Sigma_X 0.3364 mm
/Beam/Sigma_Y 0.3933 mm

/Geometry/Collimator false
/Geometry/Magnetic_Field_Value 4.0000 tesla
/Geometry/Magnetic_Field_Mapping false
/Geometry/CAD_MESH false
/Geometry/SiDeadLayer_Thickness 100.00 nm
/Geometry/Detectors -0.50 1.82 0.70 0.00 0.00
/Geometry/Catcher_Position_x 0.00 mm
/Geometry/Catcher_Position_y 2.14 mm
/Geometry/Catcher_Position_z 0.00 mm
/Geometry/Catcher_Position catcher1     #position:[source / catcher2 / catcher1]
/Geometry/Catcher_Angle 0.00 deg
/Geometry/Catcher_Thickness_Al1 300 nm
/Geometry/Catcher_Thickness_Mylar 510 nm
/Geometry/Catcher_Thickness_Al2 300 nm

/Geometry/MCP false
/Geometry/MCP_Position 0 0 0

/run/reinitializeGeometry

#---------------------------------------------------------------
#   Generate Events
#---------------------------------------------------------------
/run/printProgress 100000
/Run/File test.root
/run/beamOn 10
