#---------------------------------------------------------------
#   Verbosity
#---------------------------------------------------------------
/Phys/Cuts 1 mm
/Phys/SiliconCuts 1 um
/Phys/PlasticStep 1 mm
/Phys/StepMax 1 mm
/run/initialize
/run/verbose      0
/event/verbose    0
/tracking/verbose 0

#---------------------------------------------------------------
#   Input Files
#---------------------------------------------------------------
/Input/SRIM SRIM_data/AlMylar_32Ar.root
#/Input/Ion 207Bi
/Input/CRADLE /data333/lecanuet/data/Systematics/32Ar_IAS_a1.0_b0.0.root

#/process/inactivate ionIoni
#/Input/Ion 32Ar
#/Input/Energy 30 keV
#/Input/Direction 0 0 1 
#/Input/Position 0 0 -800

#/process/inactivate eBrem
#/Input/Particle e-
#/Input/Energy 5 MeV
#/Input/Direction iso

#---------------------------------------------------------------
#   Simulation Parameters
#---------------------------------------------------------------
/Run/Threshold_PlasticScintillator 100 keV
/Run/Threads 90

## 2024 ##
#/Beam/X -0.1 mm
#/Beam/Y 0.1 mm
#/Beam/Radius 50 mm
#/Beam/Sigma_X 0.7 mm
#/Beam/Sigma_Y 0.8 mm

## 2025 ##
/Beam/X 0.05363 mm
/Beam/Y -0.4103 mm
/Beam/Radius 1000 mm
/Beam/Sigma_X 1.05 mm
/Beam/Sigma_Y 0.61 mm

/Geometry/Collimator false
/Geometry/Magnetic_Field_Value 4 tesla
/Geometry/Magnetic_Field_Mapping false
/Geometry/CAD_MESH false
/Geometry/SiDeadLayer_Thickness 100 nm
/Geometry/Detectors -0.5 1.83 0.7 0 0
/Geometry/Catcher_Position_x 0 mm
/Geometry/Catcher_Position_y 2.14 mm
/Geometry/Catcher_Position_z 0 mm
/Geometry/Catcher_Position catcher1     #position:[source / catcher2 / catcher1]
/Geometry/Catcher_Angle 0 deg
/Geometry/Catcher_Thickness_Al1 85 nm
/Geometry/Catcher_Thickness_Mylar 525 nm
/Geometry/Catcher_Thickness_Al2 85 nm

#/Geometry/Catcher_Thickness_Al1 100 nm
#/Geometry/Catcher_Thickness_Mylar 6100 nm
#/Geometry/Catcher_Thickness_Al2 110 nm

/Geometry/MCP false
/Geometry/MCP_Position 0 0 -90

/run/reinitializeGeometry

#---------------------------------------------------------------
#   Generate Events
#---------------------------------------------------------------
/run/printProgress 10000
/Run/File /data333/lecanuet/Result/Systematics/beta-bs/32Ar_IAS_2025_a1.0_b0.0_BackScattering.root
/run/beamOn 100000000
