#---------------------------------------------------------------
#   Verbosity
#---------------------------------------------------------------
#/run/initialize
/run/verbose      0
/event/verbose    0
/tracking/verbose 0

#---------------------------------------------------------------
#   Input Files
#---------------------------------------------------------------
/Input/SRIM SRIM_data/AlMylar_2021_32Ar.root
#/Input/Ion 207Bi
/Input/CRADLE ../../../../../../mnt/hgfs/shared-2/2024_DATA/SIMULATED_DATA/fe/files/32Ar_a1_b0_1.root

#---------------------------------------------------------------
#   Simulation Parameters
#---------------------------------------------------------------
/Run/Threshold_PlasticScintillator 100 keV

/Beam/X 0. mm
/Beam/Y 0. mm
/Beam/Radius 2.5 mm
/Beam/Sigma_X 0.75 mm
/Beam/Sigma_Y 0.75 mm

/Geometry/Magnetic_Field 4 tesla
/Geometry/SiDeadLayer_Thickness 100 nm
/Geometry/Catcher_Position_z 0 mm
/Geometry/Catcher_Position catcher2     #position:[source / catcher2 / catcher1]
/Geometry/Catcher_Angle 0 deg
/Geometry/Catcher_Thickness_Al1 85 nm
/Geometry/Catcher_Thickness_Mylar 525 nm
/Geometry/Catcher_Thickness_Al2 85 nm
/run/reinitializeGeometry

#---------------------------------------------------------------
#   Generate Events
#---------------------------------------------------------------
/run/printProgress 1000
/Run/File ../../../../../../mnt/hgfs/shared-2/2024_DATA/Time_test_2.root
/run/beamOn 1000000
