#---------------------------------------------------------------
#   Verbosity
#---------------------------------------------------------------
/run/initialize
/run/verbose      0
/event/verbose    0
/tracking/verbose 0

#---------------------------------------------------------------
#   Input Files
#---------------------------------------------------------------
#/input/Open_B MAGNETIC_FIELD_data/wisard_field.txt
/Input/SRIM SRIM_data/AlMylar_2021_32Ar.txt
#/Input/Ion 32Ar
/Input/CRADLE %inputCRADLE

#---------------------------------------------------------------
#   Simulation Parameters
#---------------------------------------------------------------
/Run/Threshold_PlasticScintillator 100 keV

/Beam/X 0. mm
/Beam/Y 0. mm
/Beam/Radius 2 mm
/Beam/Sigma_X 0.3 mm
/Beam/Sigma_Y 0.3 mm

/Geometry/Magnetic_Field 4 T
/Geometry/SiDeadLayer_Thickness 100 nm
/Geometry/Catcher_Position_z 0 mm
/Geometry/Catcher_Position catcher1 0 deg     position:[source / catcher2 / catcher1] #delta angle(degree)
/Geometry/Catcher_Thickness 50 500 50 nm     thickness : Al, Mylar Al (0 delete it)

#---------------------------------------------------------------
#   Generate Events
#---------------------------------------------------------------
/run/printProgress 10000
/Run/File %output
/run/beamOn %events

