#---------------------------------------------------------------
#   Verbosity
#---------------------------------------------------------------
/run/initialize
/run/verbose      0
/event/verbose    0
/tracking/verbose 0

#---------------------------------------------------------------
#   Input Files
#---------------------------------------------------------------
#/input/Open_B MAGNETIC_FIELD_data/wisard_field.txt
/Input/SRIM SRIM_data/AlMylar_32Ar.root

/Input/Energy %Energy MeV
/Input/Particle %Particle
/Input/Direction iso

#---------------------------------------------------------------
#   Simulation Parameters
#---------------------------------------------------------------
/Run/Threshold_PlasticScintillator 100 keV
/Run/Threads %threads

/Beam/X 0. mm
/Beam/Y 0. mm
/Beam/Radius 2.5 mm
/Beam/Sigma_X 0.75 mm
/Beam/Sigma_Y 0.75 mm

/Geometry/Collimator true
/Geometry/Magnetic_Field_Value 4 tesla
/Geometry/Magnetic_Field_Mapping false
/Geometry/SiDeadLayer_Thickness 100 nm
/Geometry/D1 %x %y %z
/Geometry/D2 %x %y %z
/Geometry/D3 %x %y %z
/Geometry/D4 %x %y %z
/Geometry/D5 %x %y %z
/Geometry/D6 %x %y %z
/Geometry/D7 %x %y %z
/Geometry/D8 %x %y %z
/Geometry/D1_Angle %theta deg
/Geometry/D2_Angle %theta deg
/Geometry/D3_Angle %theta deg
/Geometry/D4_Angle %theta deg
/Geometry/D5_Angle %theta deg
/Geometry/D6_Angle %theta deg
/Geometry/D7_Angle %theta deg
/Geometry/D8_Angle %theta deg
/Geometry/Catcher_Position_z 0 mm
/Geometry/Catcher_Position catcher2     #position:[source / catcher2 / catcher1]
/Geometry/Catcher_Angle 0 deg
/Geometry/Catcher_Thickness_Al1 85 nm
/Geometry/Catcher_Thickness_Mylar 525 nm
/Geometry/Catcher_Thickness_Al2 85 nm
/run/reinitializeGeometry

#---------------------------------------------------------------
#   Generate Events
#---------------------------------------------------------------
/run/printProgress 100000
/Run/File %output
/run/beamOn %events

