#!/bin/bash

RED="\e[1;31m"
GREEN="\e[1;32m"
YELLOW="\e[1;33m"
COLOR="\e[0m"



DEFAULT_N=3
DEFAULT_n=1



FERMI_change=false
GT_change=false
a_change=false
b_change=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    nucleus=*)
      Nuclei="${1#*=}"
      ;;
    N=*)
      N="${1#*=}"
      ;;
    n=*)
      n="${1#*=}"
      ;;
    CV=*)
      CV="${1#*=}"
      FERMI_change=true
      ;;
    CS=*)
      CS="${1#*=}"
      FERMI_change=true
      ;;
    CVP=*)
      CVP="${1#*=}"
      FERMI_change=true
      ;;
    CSP=*)
      CSP="${1#*=}"
      FERMI_change=true
      ;;
    CA=*)
      CA="${1#*=}"
      GT_change=true
      ;;
    CT=*)
      CT="${1#*=}"
      GT_change=true
      ;;
    CAP=*)
      CAP="${1#*=}"
      GT_change=true
      ;;
    CTP=*)
      CTP="${1#*=}"
      GT_change=true
      ;;
    a=*)
      a="${1#*=}"
      a_change=true
      ;;
    b=*)
      b="${1#*=}"
      b_change=true
      ;;
    *)
      echo "Argument inconnu : $1"
      exit 1
      ;;
  esac
  shift
done

###default value
DEFAULT_CV=1
DEFAULT_CVP=1
DEFAULT_CS=0
DEFAULT_CSP=0

DEFAULT_CA=1.27
DEFAULT_CAP=1.27
DEFAULT_CT=0
DEFAULT_CTP=0

DEFAULT_a=1
DEFAULT_b=0

###Fermi
CV=${CV:-$DEFAULT_CV}
CVP=${CVP:-$DEFAULT_CVP}
CS=${CS:-$DEFAULT_CS}
CSP=${CSP:-$DEFAULT_CSP}
###Gamow-Teller
CA=${CA:-$DEFAULT_CA}
CAP=${CAP:-$DEFAULT_CAP}
CT=${CT:-$DEFAULT_CT}
CTP=${CTP:-$DEFAULT_CTP}

a=${a:-$DEFAULT_a}
b=${b:-$DEFAULT_b}

nProcess=${n:-$DEFAULT_n}
RunEnd=${N:-$DEFAULT_N}


if $a_change || $b_change; then
  constants="a${a}_b${b}"
  replace="s/%CS/${CS}/g; s/%CPS/${CSP}/g; s/%CV/${CV}/g; s/%CPV/${CVP}/g; s/%CA/${CA}/g; s/%CPA/${CAP}/g; s/%CT/${CT}/g; s/%CPT/${CTP}/g; s/%a/${a}/g; s/%b/${b}/g"
else
  replace="s/%CS/${CS}/g; s/%CPS/${CSP}/g; s/%CV/${CV}/g; s/%CPV/${CVP}/g; s/%CA/${CA}/g; s/%CPA/${CAP}/g; s/%CT/${CT}/g; s/%CPT/${CTP}/g; s/%a/NaN/g; s/%b/NaN/g"
fi


if $FERMI_change && ! $GT_change; then
  constants="CS${CS}_CSP${CSP}_CV${CV}_CVP${CVP}"
fi 
if ! $FERMI_change && $GT_change; then
  constants="CA${CA}_CAP${CAP}_CT${CT}_CTP${CTP}"
fi
if $FERMI_change && $GT_change; then
  constants="CA${CA}_CAP${CAP}_CT${CT}_CTP${CTP}_CS${CS}_CSP${CSP}_CV${CV}_CVP${CVP}"
fi



if [ "$Nuclei" == "32Ar" ]; then
    A=32
    Z=18
fi
if [ "$Nuclei" == "20Mg" ]; then
    A=20
    Z=12
fi
if [ "$Nuclei" == "28S" ]; then
    A=28
    Z=16
fi
if [ "$Nuclei" == "24Si" ]; then
    A=24
    Z=14
fi
if [ "$Nuclei" == "14O" ]; then
    A=14
    Z=8
fi

echo -e "$RED"
rm -vf "LOG/During_$Nuclei.txt"
echo -e "$COLOR"

TimeStart=$SECONDS

Analysis="wisard"

RunStart=1
TH=()
THRun=()
Saver=0
RunN=$(($RunStart+$nProcess))
TimeCheck=60 # in seconds

Saver=$RunStart
i=0

rootCRADLEfile="../../../../../../mnt/hgfs/shared/data/"
rootGeant4file="../../../../../../mnt/hgfs/shared/"

while [ $Saver -le $RunEnd ]; do
    th=${TH[i]}
    run=${THRun[i]}
    if kill -0 $th >/dev/null 2>&1; then
	      file_path="${rootGeant4file}${Nuclei}_${constants}_${run}.root"
        if [ $(($(date +%s)-$(stat -c %Y "$file_path"))) -ge 600 ]; then
            # Le processus est bloqué depuis plus de 10 min, on le tue
            echo "Process $th stopped more than 10 min.  Killing process..."
            kill $th
            rm "${rootCRADLEfile}${Nuclei}_${constants}_${run}.txt"
            #rm "../config/config_${constants}.txt"


        fi
    else
        TimeCurrent=$SECONDS
        DureeCurrent=$(($TimeCurrent-$TimeStart))
        SecondCurrent=$(printf "%02d" "$(($DureeCurrent%60))")
        MinuteCurrent=$(printf "%02d" "$((($DureeCurrent/60)%60))")
        HeureCurrent=$(printf "%02d" "$((($DureeCurrent/3600)%24))")
        JourCurrent=$(printf "%d" "$((($DureeCurrent/(3600*24))))")
        RunKilled=$run
        if [[ $Saver -gt $RunN ]]; then
            echo "Duree Run $RunKilled : ${JourCurrent}j:${HeureCurrent}h:${MinuteCurrent}m:${SecondCurrent}s" >> "LOG/During_$Nuclei.txt"
        fi


        cp macro_base.mac tempory/macro_${Saver}_${Nuclei}_${constants}_bis.mac
        sed -e "s/%inputCRADLE/${Nuclei}_${constants}_${Saver}.txt/g; s/%inputSRIM/${Nuclei}.txt/g" tempory/macro_${Saver}_${Nuclei}_${constants}_bis.mac > tempory/macro_${Saver}_${Nuclei}_${constants}.mac
        rm tempory/macro_${Saver}_${Nuclei}_${constants}_bis.mac
        cmdAnalysis="${Analysis} tempory/macro_${Saver}_${Nuclei}_${constants}.mac ${rootGeant4file}${Nuclei}_${constants}_${Saver}"
        echo -e "$GREEN $cmdAnalysis $COLOR"

	cd ../CRADLE-master/build
        cp ../config/config_base.txt config_${constants}_bis.txt
        sed -e "$replace" config_${constants}_bis.txt > ../config/config_${constants}.txt
        rm config_${constants}_bis.txt
        ./CRADLE++ nucleus --name ${A}${Nuclei} -Z $Z -A $A -c ../config/config_${constants}.txt general -l 1000000 -o ../${rootCRADLEfile}${Nuclei}_${constants}_${Saver}.txt
        cd -
        $cmdAnalysis &

        TH[$i]=${!}
        THRun[$i]=$Saver
        Saver=$(($Saver+1))
    fi
    i=$(($i+1))
    if [ $i -eq $nProcess ]; then
        i=0
        sleep $TimeCheck
    fi
done

wait
TimeEnd=$SECONDS

Duree=$(($TimeEnd-$TimeStart))
Second=$(printf "%02d" "$(($Duree%60))")
Minute=$(printf "%02d" "$((($Duree/60)%60))")
Heure=$(printf "%02d" "$((($Duree/3600)%24))")
Jour=$(printf "%d" "$((($Duree/(3600*24))))")
echo -e "$RED Duree total : ${Jour}"
