#---------------------------------------------------------------
#
# execution:
#       /control/execute run.mac
#
#---------------------------------------------------------------
# verbose levels
/run/verbose      0
/event/verbose    0
/tracking/verbose 0
#
#
#---------------------------------------------------------------
#   generate events
#---------------------------------------------------------------
#
#
#
/input/openFile ../../../../../../mnt/hgfs/shared/data/Ar_a1_b0_9.txt
#/run/printProgress 1
/run/beamOn 1000000
/input/closeFile
#
#
