#---------------------------------------------------------------
#
# execution:
#       /control/execute run.mac
#
#---------------------------------------------------------------
# verbose levels
/run/verbose      0
/event/verbose    0
/tracking/verbose 0
#
#
#---------------------------------------------------------------
#   generate events
#---------------------------------------------------------------
#
#
#
/input/openFile ../../../../../../mnt/hgfs/shared/data/Ar_CA1.27_CAP1.27_CT0_CTP0_CS0_CSP0_CV1_CVP1_2.txt
#/run/printProgress 1
/run/beamOn 1000000
/input/closeFile
#
#
