#---------------------------------------------------------------
#   Verbosity
#---------------------------------------------------------------
/run/initialize
/run/verbose      0
/event/verbose    0
/tracking/verbose 0

#---------------------------------------------------------------
#   Input Files
#---------------------------------------------------------------
/input/Open_B wisard_field.txt
/input/Open_SRIM SRIM_data/32Ar.txt
/input/Open_CRADLE ../../../../../../mnt/hgfs/shared/data/32Ar_a1_b0_2.txt

#---------------------------------------------------------------
#   Simulation Parameters
#---------------------------------------------------------------
/Magnetic_Field 4 T
/Threshoold_PlasticScintillator 100 keV
#/Delta_Position_Threshoold_PlasticScintillator

#---------------------------------------------------------------
#   Systematic Variables
#---------------------------------------------------------------
/SiDeadLayer_Thickness 100 nm
/Beam_Size 2 mm 300 um
/Beam_Position 0 cm 0 cm
/Catcher_Position_z 0 mm
/CatcherMylar_Thickness 0.5 um

#---------------------------------------------------------------
#   Generate Events
#---------------------------------------------------------------
/run/printProgress 10000
/output ../../../../../../mnt/hgfs/shared/32Ar_a1_b0_2.root
/run/beamOn 1000
