#---------------------------------------------------------------
#
# execution:
#       /control/execute run.mac
#
#---------------------------------------------------------------
# verbose levels
/run/verbose      0
/event/verbose    0
/tracking/verbose 0
#
#
#---------------------------------------------------------------
#   generate events
#---------------------------------------------------------------
#
#
#
/input/Open_SRIM SRIM_data/32Ar.txt
/input/Open_CRADLE ../../../../../../mnt/hgfs/shared/data/32Ar_a1_b0_1.txt
#/run/printProgress 1
/run/beamOn 1000000
/input/closeFile
#
#
